/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class FrVector extends java.util.AbstractList<Fr> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FrVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(FrVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MclJNI.delete_FrVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public FrVector(Fr[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (Fr element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public FrVector(Iterable<Fr> initialElements) {
    this();
    for (Fr element : initialElements) {
      doAdd(element);
    }
  }

  public Fr get(int index) {
    return doGet(index);
  }

  public Fr set(int index, Fr e) {
    return doSet(index, e);
  }

  public boolean add(Fr e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Fr e) {
    modCount++;
    doAdd(index, e);
  }

  public Fr remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public FrVector() {
    this(MclJNI.new_FrVector__SWIG_0(), true);
  }

  public FrVector(FrVector other) {
    this(MclJNI.new_FrVector__SWIG_1(FrVector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return MclJNI.FrVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MclJNI.FrVector_clear(swigCPtr, this);
  }

  public FrVector(int count, Fr value) {
    this(MclJNI.new_FrVector__SWIG_2(count, Fr.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return MclJNI.FrVector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    MclJNI.FrVector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return MclJNI.FrVector_doSize(swigCPtr, this);
  }

  private void doAdd(Fr x) {
    MclJNI.FrVector_doAdd__SWIG_0(swigCPtr, this, Fr.getCPtr(x), x);
  }

  private void doAdd(int index, Fr x) {
    MclJNI.FrVector_doAdd__SWIG_1(swigCPtr, this, index, Fr.getCPtr(x), x);
  }

  private Fr doRemove(int index) {
    return new Fr(MclJNI.FrVector_doRemove(swigCPtr, this, index), true);
  }

  private Fr doGet(int index) {
    return new Fr(MclJNI.FrVector_doGet(swigCPtr, this, index), false);
  }

  private Fr doSet(int index, Fr val) {
    return new Fr(MclJNI.FrVector_doSet(swigCPtr, this, index, Fr.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    MclJNI.FrVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
