/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.herumi.mcl;

public class G2Vector extends java.util.AbstractList<G2> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected G2Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(G2Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(G2Vector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MclJNI.delete_G2Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @SuppressWarnings("this-escape")
  public G2Vector(G2[] initialElements) {
    this();
    doReserve(initialElements.length);

    for (G2 element : initialElements) {
      doAdd(element);
    }
  }

  @SuppressWarnings("this-escape")
  public G2Vector(Iterable<G2> initialElements) {
    this();
    for (G2 element : initialElements) {
      doAdd(element);
    }
  }

  public G2 get(int index) {
    return doGet(index);
  }

  public G2 set(int index, G2 e) {
    return doSet(index, e);
  }

  public boolean add(G2 e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, G2 e) {
    modCount++;
    doAdd(index, e);
  }

  public G2 remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public int capacity() {
    return doCapacity();
  }

  public void reserve(int n) {
    doReserve(n);
  }

  public G2Vector() {
    this(MclJNI.new_G2Vector__SWIG_0(), true);
  }

  public G2Vector(G2Vector other) {
    this(MclJNI.new_G2Vector__SWIG_1(G2Vector.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return MclJNI.G2Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MclJNI.G2Vector_clear(swigCPtr, this);
  }

  public G2Vector(int count, G2 value) {
    this(MclJNI.new_G2Vector__SWIG_2(count, G2.getCPtr(value), value), true);
  }

  private int doCapacity() {
    return MclJNI.G2Vector_doCapacity(swigCPtr, this);
  }

  private void doReserve(int n) {
    MclJNI.G2Vector_doReserve(swigCPtr, this, n);
  }

  private int doSize() {
    return MclJNI.G2Vector_doSize(swigCPtr, this);
  }

  private void doAdd(G2 x) {
    MclJNI.G2Vector_doAdd__SWIG_0(swigCPtr, this, G2.getCPtr(x), x);
  }

  private void doAdd(int index, G2 x) {
    MclJNI.G2Vector_doAdd__SWIG_1(swigCPtr, this, index, G2.getCPtr(x), x);
  }

  private G2 doRemove(int index) {
    return new G2(MclJNI.G2Vector_doRemove(swigCPtr, this, index), true);
  }

  private G2 doGet(int index) {
    return new G2(MclJNI.G2Vector_doGet(swigCPtr, this, index), false);
  }

  private G2 doSet(int index, G2 val) {
    return new G2(MclJNI.G2Vector_doSet(swigCPtr, this, index, G2.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    MclJNI.G2Vector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
